name: freesmoking
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.18
  cupertino_icons: ^1.0.2
  duration: ^3.0.11
  easy_localization: ^3.0.1
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  provider: ^6.0.3
  time_machine: ^0.9.17
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis-Regular.ttf
        - asset: assets/fonts/Dosis-ExtraBold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
